language: node_js
sudo: required
services:
  - docker
before_install:
  - docker build  -t fadlm/docker-react -f Dockerfile.dev .
install:
  - npm i -g npm@2.15.1

scripts:
  -  docker run fadlm/docker-react npm run test -- --coverage