sudo: required
services:
  - docker

before_install:
  - gem install rake
  - docker build  -t fadlm/docker-react -f Dockerfile.dev .

scripts:
  -  docker run fadlm/docker-react npm run test -- --coverage