language: generic
sudo: required
services:
  - docker
before_install:
  - docker build  -t fadlm/docker-react -f Dockerfile.dev .
install:
  - npm i -g npm@2.15.1
scripts:
  - docker run -e CI=true fadlm/docker-react npm run test

  deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-171208721062"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
      secure: "$AWS_SECRET_KEY"