language: generic
sudo: required
services:
  - docker
before_install:
  - docker build  -t fadlm/docker-react -f Dockerfile.dev .
install:
  - npm i -g npm@2.15.1
scripts:
  - docker run -e CI=true fadlm/docker-react npm run test